version: 2

sources:
  - name: staging
    description: Catalunya data staging layer
    schema: catalunya_data_dev
    # Configure for Athena targets
    meta:
      external_location: "s3://{{ var('data_bucket') }}/staging/"
    tables:
      - name: social_services
        description: Social services data from staging parquet files
        # Athena external table configuration
        external_location: "s3://{{ var('data_bucket') }}/staging/social_services/"
        file_format: parquet
        partitioned_by:
          - name: downloaded_date
            data_type: string