version = 0.1

[default]
[default.global.parameters]
stack_name = "cloudgentgran-localstack"

[default.build.parameters]
cached = true
parallel = true

[default.validate.parameters]
lint = true

# LocalStack-specific deployment configuration
[default.deploy.parameters]
capabilities = "CAPABILITY_IAM"
confirm_changeset = false
resolve_s3 = false
s3_bucket = "cloudgentgran-sam-deployments"
s3_prefix = "sam-artifacts"
region = "us-east-1"
parameter_overrides = "Environment=local"
# Point all SAM operations to LocalStack
endpoint_url = "http://localhost:4566"

[default.package.parameters]
resolve_s3 = false
s3_bucket = "cloudgentgran-sam-deployments"
s3_prefix = "sam-artifacts"

[default.sync.parameters]
watch = true

[default.local_start_api.parameters]
warm_containers = "EAGER"

[default.local_start_lambda.parameters]
warm_containers = "EAGER"

[default.local_invoke.parameters]
parameter_overrides = "Environment=local"
env_vars = "localstack-env.json"
