# Catalunya Data Pipeline - DBT Mart Project
name: 'catalunya_marts'
version: '1.0.0'

# This setting configures which "profile" dbt uses for this project.
profile: 'catalunya_data'

# These configurations specify where dbt should look for different types of files.
model-paths: [ "models" ]
analysis-paths: [ "analyses" ]
test-paths: [ "tests" ]
seed-paths: [ "seeds" ]
macro-paths: [ "macros" ]
snapshot-paths: [ "snapshots" ]

clean-targets:
  - "target"
  - "dbt_packages"

# Variables for different environments
vars:
  # Environment-specific S3 buckets
  data_bucket: "{{ env_var('DATA_BUCKET') }}"
  catalog_bucket: "{{ env_var('CATALOG_BUCKET') }}"

# Configuring models
models:
  catalunya_marts:
    # Marts models - final tables for analytics
    marts:
      +materialized: table
      # For Athena targets, use S3 location
      +s3_data_dir: "s3://{{ env_var('DATA_BUCKET') }}/marts/"
      +s3_data_naming: schema_table
